### ISSUE TITLE
NPM package contains cypress tests 

### ISSUE THREAD

**Issue by vchan14** [norahmaria/typeach#1]
Hi, I noticed test files are bundled with the package when installing the package through NPM. 

#### Steps to reproduce: 
1. Add the package to a project `npm i typeach`
2. Navigate to components folders. e.g:  `node_modules/typeach/src/components/dialog/__tests__/Dialog.cy.ts`

I think there should be a config somewhere to exclude tests when publishing to npm.  Also, I noticed when running `npm run build` on local the artifact doesn't contain tests. 

<img width="1003" alt="image" src="https://github.com/user-attachments/assets/1dd51b77-fb34-4e95-8f3f-e2532ec0ce70">

**Comment by norahmaria** [comment]
Thank you for letting me know! ☺️

Yes, I see that right now `.npmignore` only excludes the components used in the tests and not the tests themselves. I'll update it!

For the tests not being included in the build, I'm not sure having tests for the built components is worth it right now. I'd also have to look more into it as the way it's set up right now, even if I include the test files in the build - it wouldn't produce runnable tests.

**Comment by vchan14** [comment]
You are welcome. Yes. Please don't include test files in the build. In my last paragraph, I was trying to say since your local build artifact doesn't have test files, the npm package shouldn't either. 

Nice project 👍 it helps me to config my own storybook project build.
